version: "3.9"
########################### NETWORKS
networks:
  dockervlan:
    name: dockervlan
    driver: macvlan
    driver_opts:
      parent: eth0 # using ifconfig
    ipam:
      config:
        - subnet: "192.168.1.0/24"
          ip_range: "192.168.1.110/32"
          gateway: "192.168.1.1"
 
########################### SERVICES
services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    networks:
      dockervlan:
        ipv4_address: 192.168.1.110 # IP address inside the defined range
    ports:
      - 53:53/udp
      - 67:67/udp 
      - 68:68/tcp 
      - 68:68/udp 
      - 80:80/tcp 
      - 443:443/tcp 
      - 853:853/tcp 
      - 3000:3000/tcp
    volumes:
      - ./workdir:/opt/adguardhome/work
      - ./confdir:/opt/adguardhome/conf
    restart: unless-stopped
