version: "2"
services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - 53:53/tcp #DNS
      - 53:53/udp #DNS
      - 784:784/udp  #DNS over Quic
      - 853:853/tcp #DNS over TLS
      - 3000:3000/tcp #Ersteinrichtung
      - 82:82/tcp # Admin-Webobefläche & DNS over HTTPS
      - 444:444/tcp # Admin-Webobefläche & DNS over HTTPS
    volumes:
      - ./workdir:/opt/adguardhome/work
      - ./confdir:/opt/adguardhome/conf
    restart: unless-stopped
